<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>oat</string>
  </array>
  <key>name</key>
  <string>Oat</string>
  <key>patterns</key>
  <array>
    <dict>
        <key>begin</key>
        <string>\s*/\*</string>
        <key>end</key>
        <string>\*/</string>
        <key>name</key>
        <string>comment.oat</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>"</string>
      <key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.oat</string>
				</dict>
			</dict>
      <key>captures</key>
      <dict>
          <key>0</key>
          <dict>
              <key>name</key>
              <string>string.quoted.double.oat</string>
          </dict>
      </dict>
      <key>end</key>
      <string>"</string>
      <key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.oat</string>
				</dict>
			</dict>
      <key>name</key>
      <string>constant.string.oat</string>
    </dict>
		<dict>
			<key>match</key>
			<string>;|,</string>
			<key>name</key>
			<string>punctuation.separator.oat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(null|true|false)\b</string>
			<key>name</key>
			<string>constant.language.c</string>
		</dict>
    <dict>
      <key>match</key>
      <string>\b\s*(void)|((int|bool|string)\b(\[\])*)\s*</string>
      <key>name</key>
      <string>storage.type.oat</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(\d+)</string>
      <key>name</key>
      <string>constant.numeric.oat</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\s*(\+|-|~|&gt;|&gt;&gt;|&gt;&gt;&gt;|&gt;=|&lt;|&lt;&lt;|&lt;=|&gt;=|\*|==|!=|/|\[&amp;\]|&amp;|\[\|\]|\|)\s*</string>
      <key>name</key>
      <string>keyword.operator.oat</string>
    </dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>keyword.operator.assignment.oat</string>
		</dict>
    <dict>
      <key>match</key>
      <string>\b(var|new|return|for|while|if|else)\b</string>
      <key>name</key>
      <string>keyword.control.oat</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(global|var)\b</string>
      <key>name</key>
      <string>storage.modifier.oat</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>([a-zA-Z][A-Za-z0-9_]*)\s*\(</string>
      <key>end</key>
      <string>\)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.name.function.oat</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
      </array>
      <key>name</key>
      <string>meta.function.call.oat</string>
    </dict>
    <dict>
      <key>match</key>
      <string>([a-zA-Z][A-Za-z0-9_]*)</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.oat</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.access.oat</string>
    </dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>keyword.operator.assignment.oat</string>
		</dict>

  </array>
  <key>scopeName</key>
  <string>source.oat</string>
</dict>
</plist>
